### ISSUE TITLE
add libvirt vagrant box

### ISSUE THREAD

**Issue by nbeernink** [plesk/vagrant#1]
Hi,

I was wondering if you could please add a libvirt box to the official repository in atlas. I've converted it locally using `vagrant mutate` but it would still be nice if it were to be made available publicly.

https://github.com/sciurus/vagrant-mutate

```
[niek@linux ~/git/plesk-vagrant/12.5(master)]$ vagrant mutate https://atlas.hashicorp.com/plesk/boxes/plesk-12.5/versions/1/providers/virtualbox.box libvirt
Downloading box virtualbox from https://atlas.hashicorp.com/plesk/boxes/plesk-12.5/versions/1/providers/virtualbox.box
Extracting box file to a temporary directory.
Converting virtualbox from virtualbox to libvirt.
    (100.00/100%)
Cleaning up temporary files.
The box virtualbox (libvirt) is now ready to use.

[niek@linux ~/git/plesk-vagrant/12.5(master)]$ mv ~/.vagrant.d/boxes/virtualbox/1/libvirt/ ~/.vagrant.d/boxes/plesk-VAGRANTSLASH-plesk-12.5/1/

[niek@linux ~/git/plesk-vagrant/12.5(master)]$ vagrant box list|grep plesk
plesk/plesk-12.5 (libvirt, 1)
plesk/plesk-12.5 (virtualbox, 1)
```

Running `vagrant up` then provisions a working plesk 12.5 box but using libvirt instead of virtualbox.

libvirt is used in this blogpost of fedora magazine: https://fedoramagazine.org/running-vagrant-fedora-22/

**Comment by IronButterfly** [comment]
Sorry, but we have no any plans for implementation libvirt box.

**Comment by nbeernink** [comment]
That would be a shame. Excuse me for asking but are you affiliated with Plesk? I don't see you on the [plesk roster](https://github.com/orgs/plesk/people).

For the time being I'll keep converting the boxes using the method described above.

**Comment by IronButterfly** [comment]
@nbeernink Yes, I'm from Plesk company.

**Comment by nbeernink** [comment]
I see you've been added. ;)

Alright too bad won't support the libvirt provider.
